
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "./common/Footer";
import Header from "./common/Header";
import MainLayout from "./common/MainLayout";
import "./globals.css";
import "./media.css";


export const metadata = {
  title: "Monsta Prpject",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet"/>
      </head>
      <body>
        <MainLayout>
          <Header/>
          {children}
        <Footer/>
        </MainLayout>
      </body>
    </html>
  );
}
